version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./.env:/.env
    env_file:
      - .env

  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "./init.sh"]
    environment:
      - "SECRET_KEY=#9n5v_uwn+880+53w_avj&fp!ul=wf^jlls7t+v5f^z4553i98"
      - "MODE=docker"
      - "RECON_CHEWBACCA_CRON_INTERVAL=10"
    volumes:
      - .:/code
    privileged: true
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db